# Generated by Django 4.2.26 on 2025-12-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_options_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Комедия'), ('Drama', 'Драма')], default='Не задан', max_length=25),
        ),
    ]
