# Generated by Django 4.2.26 on 2025-12-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_add',
            field=models.DateField(auto_now_add=True),
        ),
    ]
